### ISSUE TITLE
No Wiki

### ISSUE THREAD

**Issue by HatTrkPatrk** [Vineflower/vineflower-site#15]
The wiki on github links to your website, with the named purpose of migrating it over to there, but it doesn't exist there. Or at least, it's not linked to on there.

**Comment by zml2008** [comment]
What content were you looking for specifically?

**Comment by HatTrkPatrk** [comment]
> What content were you looking for specifically?

Documentation

**Comment by zml2008** [comment]
Can you be specific? This issue is not actionable without an actual ask.

**Comment by zml2008** [comment]
Closing due to a lack of information
